export enum NotifyType {
    FIRST_POST = "FIRST_POST",
    FOLLOW = "FOLLOW",
    FOLLOW_REQUEST = "FOLLOW_REQUEST",
    COMMENT = "COMMENT",
    LIKE = "LIKE",
    REPOST = "REPOST",
    MENTION = "MENTION",
    POLL_RESULT_READY = "POLL_RESULT_READY",
    PICKED_FOR_U = "PICKED_FOR_U",
}